{
 "title": "Load Generator",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Write requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(cortex_load_generator_write_req_total[$__rate_interval])) by (kind, result)",
     "legendFormat": "{{kind}}-{{result}}"
    }
   ]
  },
  {
   "title": "Samples written",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(kind) (rate(cortex_load_generator_samples_written_total[$__rate_interval]))",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "load gen queries",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "sum by (result) (rate(cortex_load_generator_queries_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "load gen compared queries",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "sum by (result) (rate(cortex_load_generator_query_results_compared_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}